name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Déclencher uniquement lorsque le code est poussé sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Cette étape permet de récupérer le code du dépôt

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Spécifier la version de Node.js à utiliser

    - name: Install dependencies
      run: npm install  # Installer les dépendances du projet

    - name: Build
      run: npm run build  # Exécuter la commande de build pour générer les fichiers statiques du projet

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Utiliser un jeton d'accès GitHub pour effectuer le déploiement
        BRANCH: gh-pages  # Branche sur laquelle déployer le projet
        FOLDER: build  # Répertoire contenant les fichiers à déployer


